### ISSUE TITLE
Error, RDB format version: 7

### ISSUE THREAD

**Issue by zhangbaolong** [helifu/redis-migration#2]
[root@localhost data]# redis-migration -sip 192.168.1.133 -sport 6379 -sauth buddy -dip 192.168.1.106 -dport 6379 -dauth buddy
   -> SYNC:000000000000/000000000000
192.168.1.133:6379 -> client 000 AUTH +OK.
192.168.1.106:6379 -> client 005 AUTH +OK.
192.168.1.106:6379 -> client 004 AUTH +OK.
192.168.1.106:6379 -> client 003 AUTH +OK.
192.168.1.106:6379 -> client 002 AUTH +OK.
192.168.1.106:6379 -> client 001 AUTH +OK.
192.168.1.133:6379 -> +FULLRESYNC (runid:237c0e8b62126e1f28e4ea6445762e7200ca1780:337)
192.168.1.133:6379 -> +FULLRESYNC +OK! (<76>ms)
192.168.1.106:6379 -> RDB migrate ...
Error, RDB format version: 7

**Comment by helifu** [comment]
the reason is that your redis version is greater than 3.2 while the RDB version is 7. you could see the 'REDIS_RDB_VERSION' in 'redis/src/rdb.h'.

currently, i have no plan to support 3.2 or 4.0. i am sorry ...
